config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :categories do
    resources :subcategories
  end
  
  resources :listings do
    collection do
      get 'search'
    end
  end
  
  root 'categories#index'

  match '/help',    to: 'pages#help',    via: :get
  match '/scams',   to: 'pages#scams',   via: :get
  match '/safety',  to: 'pages#safety',  via: :get
  match '/terms',   to: 'pages#terms',   via: :get
  match '/privacy', to: 'pages#privacy', via: :get
  match '/about',   to: 'pages#about',   via: :get
  match '/contact', to: 'pages#contact', via: :get
  match '/mylistings', to: 'listings#mylistings', via: :get
  match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :listings
  has_many :subcategories
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :category
  belongs_to :subcategory
  belongs_to :user
  validates_presence_of :user_id
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :city
  validates_presence_of :state
  
  geocoded_by :full_address
  after_validation :geocode
  
  def full_address
    [city, state, zipcode].join(', ')
  end
  
  def self.search(params)
    listings = Listing.where(category_id: params[:category].to_i)
    listings = listings.where("title LIKE ? or description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    listings = listings.near(params[:location], 20) if params[:location].present?
    listings
  end
  
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
    @community = @categories[0]
    @housing = @categories[1]
    @jobs = @categories[2]
    @personals = @categories[3]
    @services = @categories[4]
    @for_sale = @categories[5]
  end
  
  def show
    @listings = Listing.where(category_id: params[:id]).order("created_at DESC")
    @category = Category.find(params[:id])
  end
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]
  before_filter :is_user?, only: [:edit, :update, :delete]
  
  def new
    @listing = Listing.new
  end
  
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to @listing
    else
      flash[:alert] = @listing.errors.full_messages.to_sentence
      render 'new'
    end
  end
  
  def show
    @listing = Listing.find(params[:id])
  end
  
  def edit
    @listing = Listing.find(params[:id])
    @category = @listing.category
  end
  
  def update
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)
    redirect_to @listing
  end
  
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to root_path
  end
  
  def search
    @listings = Listing.search(params)
  end
  
  def mylistings
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end
  
  private
  
  def listing_params
    params.require(:listing).permit(:title, :description, :city, :state, :zipcode, :category_id, :subcategory_id)
  end
  
  def is_user?
    @listing = Listing.find(params[:id])
    unless current_user = @listing.user
      redirect_to root_path, alert: "Sorry, you are not the user of this listing."
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def help
  end
  
  def scams
  end
  
  def saftey
  end
  
  def terms
  end
  
  def privacy
  end
  
  def about
  end
  
  def contact
  end
  
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  
  def show
    @listings = Listing.where(subcategory_id: params[:id]).order("created_at DESC")
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:id])
  end
  
  def find_by_category
    category = Category.find(params[:category_id])
    subcategories = category.subcategories.find_all
    render json: { subcategories: subcategories }
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="container">
  <div class="leftbar">
    <h1><%= link_to 'rubyslist', root_path %></h1>
    <ul>
      <li><%= link_to 'post to classifieds', new_listing_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'my account', edit_user_registration_path %></li>
        <li><%= link_to 'log out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'my listings', mylistings_path %></li>
      <% else %>
        <li><%= link_to 'sign in', new_user_session_path %></li>
        <li><%= link_to 'sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
      <%= form_tag search_listings_path, method: :get do |f| %>
        <p>search rubyslist</p>
        <%= text_field_tag :search, nil, placeholder: 'search' %>
        <%= text_field_tag :location, nil, placeholder: 'near' %>
        <%= select_tag :category, options_for_select(Category.all.map{ |c| [c.name, c.id]}) %>
        <%= submit_tag '>' %>
      <% end %>
  </div>
  <div class="center-column" >
    <div class="center-one">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'community', category_path(@community) %></th>
        </tr>
        <tr>
          <td>
            <% @community.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name, category_subcategory_path(@community, subcategory) %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'personals', category_path(@personals) %></th>
        </tr>
        <tr>
          <td>
            <% @personals.subcategories.each do |subcategory| %>
            <ul>
              <li><%= link_to subcategory.name, category_subcategory_path(@personals, subcategory) %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'services', category_path(@services) %></th>
        </tr>
        <tr>
          <td>
            <% @services.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name, category_subcategory_path(@services, subcategory) %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="center-two">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'housing', category_path(@housing) %></th>
        </tr>
        <tr>
          <td>
           <% @housing.subcategories.each do |subcategory| %>
            <ul>
              <li><%= link_to subcategory.name, category_subcategory_path(@housing, subcategory) %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'for sale', category_path(@for_sale) %></th>
        </tr>
        <tr>
          <td>
            <% @for_sale.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name, category_subcategory_path(@for_sale, subcategory) %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="center-three">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'jobs', category_path(@jobs) %></th>
        </tr>
        <tr>
          <td>
            <% @jobs.subcategories.each do |subcategory| %>
            <ul>
              <li><%= link_to subcategory.name, category_subcategory_path(@jobs, subcategory) %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="rightbar">
    <ul class="rightbar-top">
      <li><%= link_to 'help and faq', help_path %></li>
      <li><%= link_to 'avoid scams and fraud', scams_path %></li>
      <li><%= link_to 'personal saftey tips', safety_path %></li>
      <li class="rightbar-top"><%= link_to 'terms of use', terms_path %></li>
      <li><%= link_to 'privacy policy', privacy_path %></li>
      <li><%= link_to 'about rubyslist', about_path %></li>
      <li><%= link_to 'contact us', contact_path %></li>
    </ul>
  </div>
</div>

app/views/categories/show.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > <%= @category.name %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
     <div class="newest">newest</div>
     <div class="oldest">oldest</div>
     <div class="highest-price">highest-price</div>
     <div class="lowest-price">lowest-price</div>
   </div>
  <ul class="list-margin">
    <% if @listings.present? %>
      <% @listings.each do |listing| %>
      <li>
        <span>
          <%= listing.created_at.strftime('%B %d, %Y') %>
        </span> 
        <%= link_to listing.title, listing %> - (<%= listing.city %>, <%= listing.state %>)
      </li>
      <% end %>
    <% else %>
      <p>No listings found!</>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyslist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= slide_down_alerts %>
<%= yield %>

</body>
</html>

app/views/listings/edit.html.erb
<%= javascript_include_tag 'listings.js' %>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      rubyslist > jobs > accounting
    </div>
  </div>
</div>
<div class="container">
  <div id="contact-area">
    <%= form_for @listing do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :description %>
      <%= f.text_area :description %>
      <p>
        <%= f.label :category_id %>
        <%= f.select :category_id, Category.all.map { |f| [f.name, f.id]} %>
      </p>
      <p>
        <%= f.label :subcategory_id %>
        <%= f.select :subcategory_id, options_for_select([]) %>
      </p>
      <%= f.label :city %>
      <%= f.text_field :city %>
      <%= f.label :state %>
      <%= f.text_field :state %>
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: "zip-width", maxlength: "5" %>
      <%= f.submit class: "create-button" %>
    <% end %>
  </div>
</div>

app/views/listings/mylistings.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > my listings
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
     <div class="newest">newest</div>
     <div class="oldest">oldest</div>
     <div class="highest-price">highest-price</div>
     <div class="lowest-price">lowest-price</div>
   </div>
  <ul class="list-margin">
    <% if @listings.present? %>
      <% @listings.each do |listing| %>
      <li>
        <span>
          <%= listing.created_at.strftime('%B %d, %Y') %>
        </span> 
        <%= link_to listing.title, listing %> - (<%= listing.city %>, <%= listing.state %>)
      </li>
      <% end %>
    <% else %>
      <p>No listings found!</>
    <% end %>
  </ul>
</div>

app/views/listings/new.html.erb
<%= javascript_include_tag 'listings.js' %>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > new listing
    </div>
  </div>
</div>
<div class="container">
  <div id="contact-area">
    <%= form_for @listing do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :description %>
      <%= f.text_area :description %>
      <p>
        <%= f.label :category_id %>
        <%= f.select :category_id, Category.all.map { |f| [f.name, f.id]} %>
      </p>
      <p>
        <%= f.label :subcategory_id %>
        <%= f.select :subcategory_id, options_for_select([]) %>
      </p>
      <%= f.label :city %>
      <%= f.text_field :city %>
      <%= f.label :state %>
      <%= f.text_field :state %>
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: "zip-width", maxlength: "5" %>
      <%= f.submit class: "create-button" %>
    <% end %>
  </div>
</div>

app/views/listings/search.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > search
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
     <div class="newest">newest</div>
     <div class="oldest">oldest</div>
     <div class="highest-price">highest-price</div>
     <div class="lowest-price">lowest-price</div>
   </div>
  <ul class="list-margin">
    <% if @listings.present? %>
      <% @listings.each do |listing| %>
      <li>
        <span>
          <%= listing.created_at.strftime('%B %d, %Y') %>
        </span> 
        <%= link_to listing.title, listing %> - (<%= listing.city %>, <%= listing.state %>)
      </li>
      <% end %>
    <% else %>
      <p>No listings found!</>
    <% end %>
  </ul>
</div>

app/views/listings/show.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > <%= link_to @listing.category.name, category_path(@listing.category) %> > <%= @listing.subcategory.name %>
    </div>
  </div>
</div>
<div class="container">
  <div>
    <button type="button">reply</button>
    posted <%= time_ago_in_words(@listing.created_at) %>
    <h1 class="listing-header"><%= @listing.title %></h1>
    <div class="box">
      <% if @listing.user = current_user %>
        <p><%= link_to 'edit', edit_listing_path %></p>
      <p><%= link_to 'delete', @listing, data: {confirm: "Are you sure you want to delete this listing?" }, method: :delete %></p>
      <% end %>
    </div>
    <p><%= @listing.description %></p>
  </div>
  <footer>
    <p>post id: <%= @listing.id %></p>
    <p>posted <%= time_ago_in_words(@listing.created_at) %></p>
  </footer>
</div>

app/views/pages/about.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > about us
    </div>
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/contact.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > contact
    </div>
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/help.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > help
    </div>
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/privacy.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > privacy
    </div>
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/safety.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > safety
    </div>
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/scams.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to 'rubyslist', root_path %> > scams
    </div>
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>